=head1 NAME

XML::LibXML::CDATASection - The DOM CDATASection Class

=head1 SYNOPSIS

  use XML::LibXML::CDATASection;

  $node = XML::LibXML::Comment( $content );

=head1 DESCRIPTION

This class provides all functions of B<XML::LibXML::Text>,
but for CDATA nodes.

=head2 Methods

=over 4

=item B<new>

The constructor is the only provided function for this
package. It is required, because B<libxml2> treats the
different textnode types slightly different.

=back

=head1 SEE ALSO

XML::LibXML, XML::LibXML::Node, XML::LibXML::Element, XML::LibXML::Text, XML::LibXML::Document

=head1 VERSION

0.90_a

