requires 'Alien::Libxml2', '0.14';

requires 'XML::NamespaceSupport', '1.07';
requires 'XML::SAX', '0.11';
requires 'XML::SAX::Base';

# author / release testing
on 'develop' => sub {
    requires 'Test::CPAN::Changes';
    requires 'Test::Kwalitee';
    requires 'Test::Pod';
    requires 'Test::TrailingSpace';
};
